name: Distribute

on:
  push:
    tags:
    - '*'

jobs:
  create_releases:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: yarn && cd scripts && yarn && cd ..

    - name: Create release
      if: startsWith(github.ref, 'refs/tags/')
      run: node scripts/createRelease.js ${{ github.ref }}

    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        body_path: release/body.txt
        files: |
            release/**/!(body.txt)


