name: Docs

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - run: yarn
    - run: yarn docs

    - name: GH Pages deploy
      uses: Cecilapp/GitHub-Pages-deploy@3.1.0
      with:
        email: essmale2005@gmail.com
        cname: hindenburg.js.org
        build_dir: docs
        branch: gh-pages
